// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: proto/Warframes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarframeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *WarframeRequest) Reset() {
	*x = WarframeRequest{}
	mi := &file_proto_Warframes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarframeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarframeRequest) ProtoMessage() {}

func (x *WarframeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Warframes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarframeRequest.ProtoReflect.Descriptor instead.
func (*WarframeRequest) Descriptor() ([]byte, []int) {
	return file_proto_Warframes_proto_rawDescGZIP(), []int{0}
}

func (x *WarframeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WarframeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Level int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *WarframeResponse) Reset() {
	*x = WarframeResponse{}
	mi := &file_proto_Warframes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarframeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarframeResponse) ProtoMessage() {}

func (x *WarframeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Warframes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarframeResponse.ProtoReflect.Descriptor instead.
func (*WarframeResponse) Descriptor() ([]byte, []int) {
	return file_proto_Warframes_proto_rawDescGZIP(), []int{1}
}

func (x *WarframeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WarframeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WarframeResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type NewWarframeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Level int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *NewWarframeRequest) Reset() {
	*x = NewWarframeRequest{}
	mi := &file_proto_Warframes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWarframeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWarframeRequest) ProtoMessage() {}

func (x *NewWarframeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Warframes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWarframeRequest.ProtoReflect.Descriptor instead.
func (*NewWarframeRequest) Descriptor() ([]byte, []int) {
	return file_proto_Warframes_proto_rawDescGZIP(), []int{2}
}

func (x *NewWarframeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewWarframeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NewWarframeRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type AddWarframesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *AddWarframesResponse) Reset() {
	*x = AddWarframesResponse{}
	mi := &file_proto_Warframes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWarframesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWarframesResponse) ProtoMessage() {}

func (x *AddWarframesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Warframes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWarframesResponse.ProtoReflect.Descriptor instead.
func (*AddWarframesResponse) Descriptor() ([]byte, []int) {
	return file_proto_Warframes_proto_rawDescGZIP(), []int{3}
}

func (x *AddWarframesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_Warframes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Warframes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_Warframes_proto_rawDescGZIP(), []int{4}
}

type WarframeTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WarframeTimeRequest) Reset() {
	*x = WarframeTimeRequest{}
	mi := &file_proto_Warframes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarframeTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarframeTimeRequest) ProtoMessage() {}

func (x *WarframeTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Warframes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarframeTimeRequest.ProtoReflect.Descriptor instead.
func (*WarframeTimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_Warframes_proto_rawDescGZIP(), []int{5}
}

func (x *WarframeTimeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_proto_Warframes_proto protoreflect.FileDescriptor

var file_proto_Warframes_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x22, 0x25, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x10, 0x57, 0x61, 0x72, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x52, 0x0a, 0x12, 0x4e, 0x65,
	0x77, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x2c,
	0x0a, 0x14, 0x41, 0x64, 0x64, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x29, 0x0a, 0x13, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x32, 0xbf, 0x02, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x57, 0x61, 0x72,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0d, 0x67, 0x65, 0x74, 0x57, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0f,
	0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1a, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4e, 0x0a,
	0x0c, 0x61, 0x64, 0x64, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1c, 0x2e,
	0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x72, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x57, 0x61,
	0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x53, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x42, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x57,
	0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x57, 0x61, 0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x57, 0x61,
	0x72, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x50, 0x72, 0x6f, 0x79, 0x65, 0x63, 0x74, 0x6f, 0x5f, 0x67,
	0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Warframes_proto_rawDescOnce sync.Once
	file_proto_Warframes_proto_rawDescData = file_proto_Warframes_proto_rawDesc
)

func file_proto_Warframes_proto_rawDescGZIP() []byte {
	file_proto_Warframes_proto_rawDescOnce.Do(func() {
		file_proto_Warframes_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Warframes_proto_rawDescData)
	})
	return file_proto_Warframes_proto_rawDescData
}

var file_proto_Warframes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_Warframes_proto_goTypes = []any{
	(*WarframeRequest)(nil),      // 0: Warframe.WarframeRequest
	(*WarframeResponse)(nil),     // 1: Warframe.WarframeResponse
	(*NewWarframeRequest)(nil),   // 2: Warframe.NewWarframeRequest
	(*AddWarframesResponse)(nil), // 3: Warframe.AddWarframesResponse
	(*Empty)(nil),                // 4: Warframe.Empty
	(*WarframeTimeRequest)(nil),  // 5: Warframe.WarframeTimeRequest
}
var file_proto_Warframes_proto_depIdxs = []int32{
	0, // 0: Warframe.WarframeService.GetWaframeInfo:input_type -> Warframe.WarframeRequest
	4, // 1: Warframe.WarframeService.getWarameList:input_type -> Warframe.Empty
	2, // 2: Warframe.WarframeService.addWarframes:input_type -> Warframe.NewWarframeRequest
	5, // 3: Warframe.WarframeService.GetWarframesByType:input_type -> Warframe.WarframeTimeRequest
	1, // 4: Warframe.WarframeService.GetWaframeInfo:output_type -> Warframe.WarframeResponse
	1, // 5: Warframe.WarframeService.getWarameList:output_type -> Warframe.WarframeResponse
	3, // 6: Warframe.WarframeService.addWarframes:output_type -> Warframe.AddWarframesResponse
	1, // 7: Warframe.WarframeService.GetWarframesByType:output_type -> Warframe.WarframeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Warframes_proto_init() }
func file_proto_Warframes_proto_init() {
	if File_proto_Warframes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Warframes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Warframes_proto_goTypes,
		DependencyIndexes: file_proto_Warframes_proto_depIdxs,
		MessageInfos:      file_proto_Warframes_proto_msgTypes,
	}.Build()
	File_proto_Warframes_proto = out.File
	file_proto_Warframes_proto_rawDesc = nil
	file_proto_Warframes_proto_goTypes = nil
	file_proto_Warframes_proto_depIdxs = nil
}
